spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://192.168.1.6:3306/ecommerce?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_ROOT_PASSWORD:pbhyclls}
    hikari:
      connection-timeout: 5000
    driver-class-name: com.mysql.cj.jdbc.Driver

    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:29092}

  mail:
    from: nkswin@gmail.com
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER:kwinn0332@gmail.com}
    password: ${EMAIL_PASSWORD:erjfxxbvzlcfpvqj}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG